version: 2

sources:
  - name: cricket_raw
    description: "Raw cricket match data from external tables"
    schema: cricket_data
    tables:
      - name: matches
        description: "Cricket match data with teams, venues, and outcomes"
        columns:
          - name: match_date
            description: "Date when the match was played"
          - name: match_type_detail
            description: "Type of cricket match (T20, ODI, Test, etc.)"
          - name: winner
            description: "Team that won the match"
          - name: team_1
            description: "First team in the match"
          - name: team_2
            description: "Second team in the match"
          - name: venue
            description: "Stadium where the match was played"
          - name: city
            description: "City where the match was played"
          - name: toss_decision
            description: "Captain's decision after winning toss"
          - name: toss_winner
            description: "Team that won the toss"
